routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});


Route::get('/', 'FrontController@index');
Route::get('/feed', 'FeedController@index');
Route::get('/about', 'AboutController@index');
Route::get('/findpeople', 'FindPeopleController@index');
Route::get('/contact', 'ContactController@index');
Route::get('/faq', 'FaqController@index');
Route::get('/plan', 'PlanController@index');

Route::get('/influencer', 'InfluencerController@index');

Route::get('/login', 'Auth\LoginController@index');

Route::get('/signup', 'Auth\RegisterController@index');
Route::post('/create', 'Auth\RegisterController@create');




Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function() {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace

    Route::get('/dashboard', 'HomeController@index');
    Route::resource('users', 'UsersController');
    Route::resource('privacyPolicy', 'PrivacyPolicyController');
    Route::resource('faq', 'FaqController');
    Route::resource('terms', 'TermsController');
    Route::resource('aboutUs', 'AboutUsController');
    Route::resource('report', 'ReportController');
    Route::resource('email', 'EmailController');
    Route::resource('invoice', 'InvoiceController');
    Route::resource('setting', 'SettingController');
    Route::resource('notification', 'NotificationController');

//    route for category
    Route::get('/category', 'CategoryController@index');
    Route::get('/addcategory', 'CategoryController@create');
    Route::post('/store', 'CategoryController@store');

//    route for subcategory
    Route::get('/subcategory', 'SubCategoryController@index');
    Route::get('/addsubcategory', 'SubCategoryController@create');
    Route::post('/subcategorystore', 'SubCategoryController@store');

//    route for subcategory
    Route::get('/subsubcategory', 'SubSubCategoryController@index');
    Route::get('/addsubsubcategory', 'SubSubCategoryController@create');
    Route::post('/subsubcategorystore', 'SubSubCategoryController@store');
});

resources/views/admin/privacy/add_privacy.blade.php
@extends('admin.layouts.layout')
@section('title', 'Admin About Us')
<!--/ in case you want to write JS, write here/-->
@section('custom_js')

<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
    CKEDITOR.replace('summary-ckeditor');
</script>
@parent
<!--/ in case you want to write JS, write here/-->
<!--/ in case you want to write JS, write here/-->
@endsection


@section('custom_css')
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{{url('/app-assets/css/core/menu/menu-types/vertical-menu.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('/app-assets/css/plugins/extensions/swiper.css')}}">

<!-- END: Page CSS-->

@parent
<!--/ in case you want to write CSS, write here/-->

<!--/ in case you want to write CSS, write here/-->
@endsection

@section('sidebar')
@parent
<!--/ in case you want add something to Sidebar, write here/-->



<!--/ in case you want add something to Sidebar, write here/-->
@endsection

@section('content')
<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">Privacy Policy</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item"><a href="#"><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Pages</a>
                                </li>
                                <li class="breadcrumb-item active">Privacy Policy
                                </li>
                                <li class="breadcrumb-item active"><a href="{{route('privacyPolicy.create')}}">Add</a>
                                </li>
                                 <li class="breadcrumb-item active"><a href="{{route('privacyPolicy.edit',1)}}">Edit</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row">
                <h1></h1>
            </div>
                <form method="POST" action="{{route('privacyPolicy.store')}}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label>Title:</label>
                        <input type="text" name="title" class="form-control" placeholder="Title" value=""/>
                        <input type="hidden" name="slug" value="aboutUs"/>
                        
                    </div>
                    <div class="form-group">
                        <label>Description:</label>
                        <textarea class="form-control" id="summary-ckeditor" name="summary-ckeditor"></textarea>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success btn-submit">Submit</button>
                    </div>
                </form>
        </div>
    </div>
</div>
<!-- END: Content-->
@endsection

resources/views/admin/privacy/edit_privacy.blade.php
@extends('admin.layouts.layout')
@section('title', 'Admin About Us')
<!--/ in case you want to write JS, write here/-->
@section('custom_js')

<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
    CKEDITOR.replace('summary-ckeditor');
</script>
@parent
<!--/ in case you want to write JS, write here/-->
<!--/ in case you want to write JS, write here/-->
@endsection


@section('custom_css')
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{{url('/app-assets/css/core/menu/menu-types/vertical-menu.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('/app-assets/css/plugins/extensions/swiper.css')}}">

<!-- END: Page CSS-->

@parent
<!--/ in case you want to write CSS, write here/-->

<!--/ in case you want to write CSS, write here/-->
@endsection

@section('sidebar')
@parent
<!--/ in case you want add something to Sidebar, write here/-->



<!--/ in case you want add something to Sidebar, write here/-->
@endsection

@section('content')
<!-- BEGIN: Content-->
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">Privacy Policy</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item"><a href="#"><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Pages</a>
                                </li>
                                <li class="breadcrumb-item active">Privacy Policy
                                </li>
                                <li class="breadcrumb-item active"><a href="{{route('privacyPolicy.create')}}">Add</a>
                                </li>
                                 <li class="breadcrumb-item active"><a href="{{route('privacyPolicy.edit',1)}}">Edit</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row">
                <h1></h1>
            </div>
                <form method="POST" action="{{route('privacyPolicy.update',1)}}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label>Title:</label>
                        <input type="text" name="title" class="form-control" placeholder="Title" value=""/>
                        <input type="hidden" name="slug" value="aboutUs"/>
                        
                    </div>
                    <div class="form-group">
                        <label>Description:</label>
                        <textarea class="form-control" id="summary-ckeditor" name="summary-ckeditor"></textarea>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-success btn-submit">Submit</button>
                    </div>
                </form>
        </div>
    </div>
</div>
<!-- END: Content-->
@endsection

resources/views/admin/privacy/index.blade.php
@extends('admin.layouts.layout')
<!--/ in case you want to write JS, write here/-->

@section('custom_js')
<script src="{{url('/app-assets/js/scripts/pages/faq.js')}}"></script>
@parent
<!--/ in case you want to write JS, write here/-->
<!--/ in case you want to write JS, write here/-->
@endsection


@section('custom_css')
<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{{url('/app-assets/css/core/menu/menu-types/vertical-menu.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('/app-assets/css/plugins/extensions/swiper.css')}}">

<!-- END: Page CSS-->

@parent
<!--/ in case you want to write CSS, write here/-->

<!--/ in case you want to write CSS, write here/-->
@endsection

@section('sidebar')
@parent
<!--/ in case you want add something to Sidebar, write here/-->



<!--/ in case you want add something to Sidebar, write here/-->
@endsection

@section('content')
<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-12 mb-2 mt-1">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h5 class="content-header-title float-left pr-1 mb-0">Privacy Policy</h5>
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb p-0 mb-0">
                                <li class="breadcrumb-item"><a href="index.html"><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Pages</a>
                                </li>
                                <li class="breadcrumb-item active">Privacy Policy
                                </li>
                                <li class="breadcrumb-item active"><a href="{{route('privacyPolicy.create')}}">Add</a>
                                </li>
                                 <li class="breadcrumb-item active"><a href="{{route('privacyPolicy.edit',1)}}">Edit</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection